### ISSUE TITLE
v10 Support

### ISSUE THREAD

**Issue by UranusBytes** [League-of-Foundry-Developers/simplefog#78]
Simplefog support for v10 is actively underway, though very early in the process.

To be notified when an alpha release is available for testing, subscribe to notifications for this issue.

**Comment by UranusBytes** [comment]
Initial alpha release for v10 support.

Module manifest: REMOVED

Also note that absolutely NO testing of this release with v9 has been done, nor has migration from an existing v9 world be done.  Assume it will break.

**Comment by TiloBuechsenschuss** [comment]
You probably know this, but on v10 the alpha does not work. The button does not appear in the control sidebar, and the hotkey also doesn't bring out the controls.
I created a new world to test out if this is a migration issue, but nope - doesn't work on a fresh world either.

**Comment by UranusBytes** [comment]
> You probably know this, but on v10 the alpha does not work. 

No, I did not.  I made the foolish assumption that the code that was working on my system would work once committed.  😩 

A quick test implies that there is both something wrong with the manifest as well as with the HUD controls.  Thanks for the notice...

**Comment by UranusBytes** [comment]
Revised alpha release for v10 support has been posted.  This time I did more testing with what downloads from the manifest URL.  😭 

Module manifest: REMOVED

This version has still had NO testing with v9, nor has migration from an existing v9 world been tested.

**Comment by TiloBuechsenschuss** [comment]
Seems to work fine for me now. Thanks a bunch! ^-^

**Comment by Aldarana** [comment]
I just tried the module version that was linked in this thread. It seems to be working fine for me as well. I tested it on a world that had be migrated from v9. The module settings seemed to have been reset to default. The fog for the one scene I was using SimpleFog for appeared exactly as I had it laid out in v9.

**Comment by Rooksgate** [comment]
Works for me as well - thanks for the update and the module. It's a staple of my Dark Sun hex crawl.

**Comment by PanchoManSandyRavage** [comment]
I appreciate the continued work. This is working for me now too.

**Comment by MortarionUA** [comment]
Fog is working, Fog Overlay Image not (adding screenshot below). It's looks like it trying to simultaniously apply color effect end overlay effect.
![Screenshot_321](https://user-images.githubusercontent.com/17316769/191245402-e4bde75f-3acc-4def-b6ed-290a4d3a8071.jpg)

**Comment by ksignorini** [comment]
Door icons showing through the fog just like in [#23](https://github.com/League-of-Foundry-Developers/simplefog/issues/23)

**Comment by UranusBytes** [comment]
New version posted.  This has had more testing done and includes some changes around the overlay image.  Some migration testing from v9 has been done, but I would still not consider this fully "ready" for live games with players until it's had some more testing.  Any and all feedback are appreciated.

Module manifest: https://github.com/League-of-Foundry-Developers/simplefog/releases/download/0.3.0-BETA.7/module.json

**Comment by cpcodes** [comment]
I test migrated a world with a few dozen scenes and from my spot checking, all appear to have migrated without issue. The fog in those scenes has different player and GM coloring/opacity, but other than that the fog is default, so I can't confirm that migration is smooth with other options (such as image fog). Blur and Transitions are enabled.

**Comment by jasonxbergman** [comment]
I ran a session over the weekend with the preliminary v10 version. It works, but it looks like once the module is activated it's turning simplefog on for ALL scenes, and you have to manually disable it for ones where you don't want it. 

I use SF for some, but not every scene.

**Comment by HenningTimm** [comment]
I can confirm the issue observed by @jasonxbergman 

Each time I reload the world, Simplefog activates on all scenes and needs to be manually turned off for scenes that should not use it. The migration seems to have worked fine.

Thank you for your work on this!

**Comment by justinthejaguar** [comment]
> New version posted. This has had more testing done and includes some changes around the overlay image. Some migration testing from v9 has been done, but I would still not consider this fully "ready" for live games with players until it's had some more testing. Any and all feedback are appreciated.
> 
> Module manifest: https://github.com/League-of-Foundry-Developers/simplefog/releases/download/0.3.0-BETA.7/module.json

I have been using this version with success. It seems that the resetting fog issue is gone for me. Do you anticipate doing a PR for this?

**Comment by UranusBytes** [comment]
> once the module is activated it's turning simplefog on for ALL scenes, and you have to manually disable it for ones where you don't want it.

This appears to be a vestige of the module level "Auto Enable Scene Fog" being enabled.  

<img width="415" alt="image" src="https://user-images.githubusercontent.com/11236319/201484862-35de57b7-bae5-4db6-a149-ef081ba873da.png">

While I agree that this can be annoying on an initial module enabling, I'd rather err on the side of caution of fog being enabled...  Also, I'd prefer not to overcomplicate changes so I can get v10 released.  I'm going to park this for future consideration.

#92

**Comment by jmosq** [comment]
Just tried the beta build, and I get this error

![image](https://user-images.githubusercontent.com/29285713/201484993-ce9eb801-70f1-410f-ac1d-4edee31cb537.png)

**Comment by justinthejaguar** [comment]
> Just tried the beta build, and I get this error
> 
> ![image](https://user-images.githubusercontent.com/29285713/201484993-ce9eb801-70f1-410f-ac1d-4edee31cb537.png)

SimpleFog version 0.3.0 Beta7
Weird. I am not getting that. What version of FVTT are you on? Do you have all your other modules deactivated while testing? Assuming V10.290, I'd assume this is a conflict with another module.

**Comment by UranusBytes** [comment]
> Just tried the beta build, and I get this error
> 
> ![image](https://user-images.githubusercontent.com/29285713/201484993-ce9eb801-70f1-410f-ac1d-4edee31cb537.png)

This appears the same as #76  which I _thought_ I had fixed in a beta.7  Can you confirm you're running this beta.7 version?

**Comment by jmosq** [comment]
It is fixed. Sorry. I must have reverted to the old 0.2 version. Just checked with 0.3.0 and it's working. Thank you for that BTW!

**Comment by UranusBytes** [comment]
v0.3.0 has been released into the wilds...  

I am updating the manifest for 0.3.0-BETA.7 and 0.3.0-ALPHA.3 to point the full release.

**Comment by justinthejaguar** [comment]
Strange error appears on Startup.
FVTT 10.291
OSE 1.6.8
SF 0.3.1
node.js
Chrome Browser

![image](https://user-images.githubusercontent.com/38022481/209028220-8454a7e4-7368-4be9-a211-30798c61c486.png)

**Comment by ksignorini** [comment]
Still showing doors on blacked out area for players like in #23

**Comment by arcos** [comment]
Getting a new weird error:
![image](https://user-images.githubusercontent.com/143747/221285369-abf961f3-0937-4e4f-a079-84719162127a.png)

**Comment by arcos** [comment]
This fixes the issue locally for me

from `classes/MaskLayer.js` (around line 293)

```javascript
  renderStack(
    history = canvas.scene.getFlag(this.layername, "history"),
    start = this.pointer,
    stop = canvas.scene.getFlag(this.layername, "history.pointer"),
    isInit = false
  ) {
    simplefogLogDebug('MaskLayer.renderStack')
    // If history is blank, do nothing
    if (!history || !isInit) { // <<< changed this as history was often typeof undefined or nullish
      simplefogLogDebug('MaskLayer.renderStack - set visible to autoEnableSceneFog')
      this.visible = game.settings.get('simplefog', 'autoEnableSceneFog');
      return;
    }
    // If history is zero, reset scene fog
    if (history.events.length === 0) this.resetMask(false);
    if (start === undefined) start = 0;
    if (stop === undefined) stop = history.events.length;
    // If pointer preceeds the stop, reset and start from 0
    if (stop <= this.pointer) {
      this.resetMask(false);
      start = 0;
    }

```

**Comment by StealthRevealed** [comment]
This fix worked perfectly for me! Thanks arcos.
